package com.llo.randombaby.util;

public final class Genero {

    public static String[] meninos() {
        return new String[]{"Miguel", "Davi",
                "Gabriel",
                "Arthur",
                "Lucas",
                "Matheus",
                "Pedro",
                "Guilherme",
                "Gustavo",
                "Rafael",
                "Felipe",
                "Bernardo",
                "Enzo",
                "Nicolas",
                "João Pedro",
                "Pedro Henrique",
                "Cauã",
                "Vitor",
                "Eduardo",
                "Daniel",
                "Henrique",
                "Murilo",
                "Vinicius",
                "Samuel",
                "Pietro",
                "João Vitor",
                "Leonardo",
                "Caio",
                "Heitor",
                "Lorenzo",
                "Isaac",
                "Lucca",
                "Thiago",
                "João Gabriel",
                "João",
                "Theo",
                "Bruno",
                "Bryan",
                "Carlos Eduardo",
                "Luiz Felipe",
                "Breno",
                "Emanuel",
                "Ryan",
                "Vitor Hugo",
                "Yuri",
                "Benjamin",
                "Erick",
                "Enzo Gabriel",
                "Fernando",
                "Joaquim",
                "André",
                "Tomás",
                "Francisco",
                "Rodrigo",
                "Igor",
                "Antonio",
                "Ian",
                "Luiz Otávio",
                "Juan",
                "João Guilherme",
                "Diogo",
                "Otávio",
                "Nathan",
                "Calebe",
                "Danilo",
                "Luan",
                "Luiz Henrique",
                "Kaique",
                "Alexandre",
                "João Miguel",
                "Iago",
                "Ricardo",
                "Raul",
                "Marcelo",
                "Julio César",
                "Cauê",
                "Benício",
                "Vitor Gabriel",
                "Augusto",
                "Pedro Lucas",
                "Luiz Gustavo",
                "Giovanni",
                "Renato",
                "Diego",
                "João Paulo",
                "Renan",
                "Luiz Fernando",
                "Anthony",
                "Lucas Gabriel",
                "Thales",
                "Luiz Miguel",
                "Henry",
                "Marcos Vinicius",
                "Kevin",
                "Levi",
                "Enrico",
                "João Lucas",
                "Hugo",
                "Luiz Guilherme",
                "Matheus Henrique"};
    }

    public static String[] meninas() {
        return new String[]{
                "Helena",
                "Alice",
                "Laura",
                "Manuela",
                "Sophia",
                "Isabella",
                "Luísa",
                "Heloísa",
                "Cecília",
                "Maitê",
                "Eloá",
                "Elisa",
                "Liz",
                "Júlia",
                "Maria Luísa",
                "Valentina",
                "Maria Alice",
                "Lívia",
                "Antonella",
                "Lorena",
                "Ayla",
                "Isis",
                "Maria Júlia",
                "Maya",
                "Maria Clara",
                "Esther",
                "Giovanna",
                "Lara",
                "Sarah",
                "Beatriz",
                "Aurora",
                "Mariana",
                "Maria Cecília",
                "Olívia",
                "Maria Helena",
                "Isadora",
                "Luna",
                "Catarina",
                "Melissa",
                "Maria Eduarda",
                "Lavínia",
                "Agatha",
                "Emanuelly",
                "Maria",
                "Alícia",
                "Rebeca",
                "Ana Clara",
                "Yasmin",
                "Clara",
                "Marina",
                "Ana Júlia",
                "Ana Luísa",
                "Isabelly",
                "Ana Laura",
                "Rafaela",
                "Ana Liz",
                "Stella",
                "Gabriela",
                "Vitória",
                "Allana",
                "Mirella",
                "Milena",
                "Bella",
                "Ana",
                "Nicole",
                "Emilly",
                "Maria Vitória",
                "Mariah",
                "Clarice",
                "Letícia",
                "Laís",
                "Maria Liz",
                "Bianca",
                "Melina",
                "Jade",
                "Ana Beatriz",
                "Maria Fernanda",
                "Betina",
                "Maria Valentina",
                "Maria Laura",
                "Heloíse",
                "Maria Isis",
                "Zoe",
                "Louise",
                "Malu",
                "Melinda",
                "Ana Cecília",
                "Ana Lívia",
                "Ana Vitória",
                "Maria Heloísa",
                "Chloe",
                "Maria Flor",
                "Pietra",
                "Pérola",
                "Ana Sophia",
                "Maria Elisa",
                "Gabrielly",
                "Larissa",
                "Maria Eloá",
                "Eduarda"};
    }
}
